quarkus.http.port=8080
quarkus.swagger-ui.always-include=true

//CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.max-age=86400

quarkus.log.category."org.logging.LoggingClientFilter".level=INFO
quarkus.cache.caches.tv-show-cache.expire-after-write=1H